### ISSUE TITLE
TypeError on DataFrame Concatenation Due to Unhashable Type 'List'

### ISSUE THREAD

**Issue by JohnsL-U** [SWE574-G3/Living-Stories-App#108]
**Description:** `TypeError: unhashable type: 'list'` occurs when attempting to concatenate two pandas DataFrames and then applying drop_duplicates(). This issue happened within recommend_stories function. The error was triggered because some columns in our DataFrames contained lists!

**Tasks:**
- [x] Identify List Containing Columns by adding below code. 
   ```python
   columns_to_drop = [col for col in df.columns if isinstance(df[col].iloc[0], list)]
   ```
- [x] Drop Columns before concatenating the DataFrames. The relevant code change was:
   ```python
   df = df.drop(columns=columns_to_drop)
   ```
- [x] This process was applied to both DataFrames involved in the concatenation (top_recommendations and top_cluster_stories) to prevent any issues during the concatenation or duplicate removal process.
