### ISSUE TITLE
Improvements on Recommendation Engine

### ISSUE THREAD

**Issue by JohnsL-U** [SWE574-G3/Living-Stories-App#117]
**Description:** Aiming to add followed users and comments for user_interactions function. Also, need to implement stories read data into clustering technique.

**Tasks:**
- [ ] Add fetch functions to receive user read stories and user comments
- [ ] Add user read stories into user_preferred_cluster function of the clustering method to improve recommending stories
- [ ] Update user_interactions function to include comments and followed users (which already exists under check_followed_user_likes function)
