### ISSUE TITLE
Improvements on Recommendation Engine

### ISSUE THREAD

**Issue by JohnsL-U** [SWE574-G3/Living-Stories-App#118]
**Description:** Aiming to add followed users and comments for user_interactions variable. Also, need to implement stories read data into clustering technique.

**Tasks:**
- [x] Add fetch functions to receive user read stories and user comments
- [x] Add user read stories into user_preferred_cluster variable to improve recommending stories
- [x] Update user_interactions variable to include comments and followed users (which already exists under check_followed_user_likes variable)

**Comment by JohnsL-U** [comment]
Completed! See [commit](https://github.com/SWE574-G3/Living-Stories-App/commit/1a1902fe4aa1aadd05ecdccfc41eb535bbcb9b79)
