### ISSUE TITLE
Enhance Story Recommendation System with Explanation Feature

### ISSUE THREAD

**Issue by JohnsL-U** [SWE574-G3/Living-Stories-App#154]
***Description:*** Currently story recommendation system does not provide users with the reasons behind each recommendation. To improve transparency and user engagement, a feature that explains the main reason for each story's recommendation should be added. The explanations could be based on one or more of the following criteria: location similarity, label similarity, followed user liked score, clustering or most liked stories.

### Tasks:
- [x] Modify the recommend_stories function to include a reason for each recommendation.
- [x] Ensure that the reason is based on the highest contributing factor 
- [x] Update the API response to include the recommendation reason along with the story ID.
- [x] Test the implementation with various scenarios to ensure accuracy and relevance of the provided explanations.
