### ISSUE TITLE
Research Optimal Model for Recommendation Engine

### ISSUE THREAD

**Issue by JohnsL-U** [SWE574-G3/Living-Stories-App#72]
**Description:**  
We need to research and identify the most optimal model to power our Recommendation Engine. 

**Tasks:**  

- [x] Conduct research on potential models suitable for our use case.
- [x] Analyze the efficiency, accuracy, and scalability of each model.
- [x] Commit the chosen model in an "Overview Report" in the repository.
- [x]  Backend team should review the Overview Report be ready to discuss questions & concerns.

**Comment by JohnsL-U** [comment]
@yavuzsa @BurakKocak99 Can you please check out the final task and close the issue once you get a chance to review [the Report](https://github.com/SWE574-G3/Living-Stories-App/blob/recommendation-engine/recommendation_engine/Overview.md)
