### ISSUE TITLE
Create Data for Testing Recommendation Engine Performance

### ISSUE THREAD

**Issue by JohnsL-U** [SWE574-G3/Living-Stories-App#92]
**Description:**
We require synthetic data to test the performance of our recommendation engine. This task involves generating a set of 10 users and 20 stories on our web app prototype. The distribution of stories among users doesn't need to be even, but should reflect a realistic variety of user interactions with the stories. Please make sure the stories have locations, dates and likes (by other users). It would be great if you could also have some users follow each other!

**Tasks:**
- [ ] **Generate 10 Users**: Create 10 fictional user profiles with unique identifiers and relevant attributes.
- [ ] **Create 20 Stories**: Develop 20 stories, ensuring a diverse range of topics, themes, or categories.
- [ ] **Simulate Interactions**: Assign these stories to the users in a manner that mimics real user behavior (likes, follows, etc.), without evenly distributing the stories among the users.

**Comment by erhan-yasar** [comment]
More than 10 users are created in the application. You can logın them with user2@mail.com - user11@mail.com
Recommendation engine test user is Recep Oluk. User Id is 38. It has 8 dıfferent storıes and liked most of the stories at the application. You can login this account with recuser@mail.com
More than 20 stories are created in the application. 
Results are shared with the team.  http://35.246.216.172:5002/recommendations?user_id=38 results with [10,14,13] data.
These entered data are enough for testing recommendation engine performance.
