### ISSUE TITLE
Review and Provide Feedback on Alternative Recommendation Engine

### ISSUE THREAD

**Issue by JohnsL-U** [SWE574-G3/Living-Stories-App#93]
**Description:**
I have developed a [new recommendation engine model](https://github.com/SWE574-G3/Living-Stories-App/blob/recommendation-engine/recommendation_engine/rec_engineV2.py) address previous issues with database compatibility and computational logic. 

**Assumptions:**
- The model's data is sourced from our existing PostgreSQL database.
- The scoring mechanism includes label similarity, location proximity, and checks for likes by followed users.
- The scores are normalized to enhance variability and differentiation.
- 'story_labels' is a list of labels for each story

**Tasks:**
- [x] **Review the Updated Model**: Examine the changes made to the scoring logic.
- [x] **Test the Model**: Run the model with various inputs to assess its performance and the diversity of its recommendations.
- [x] **Provide Feedback**: Share any observations about the model's performance, including any potential issues or areas for improvement.

**Notes:** 
- You can test by utilizing Postman. Simply send GET request at [http://127.0.0.1:5002/recommendations?user_id=3](url) <br> The hard coded data allows use to test up to 10 users. Please see the attached image.
<img width="1039" alt="Screenshot 2023-11-25 at 9 26 21 AM" src="https://github.com/SWE574-G3/Living-Stories-App/assets/93824716/4bbc0fe7-84fc-488f-b7d4-66d58c27ab40">

**Comment by JohnsL-U** [comment]
On my next commit, I will update the code with database fetch functions!

**Comment by JohnsL-U** [comment]
Updated [recommendation engine V2](https://github.com/SWE574-G3/Living-Stories-App/blob/recommendation-engine/recommendation_engine/rec_engineV2.py) for postgre sql data fetching. Upon completion of issue #92 you can test the entire system. For the moment, simply comment out Database Functions and use the dummy data!
